%% Enumeration type ModelType_t with values:
%%
%                    ModelTypeNull:                0
%             ModelTypeUserDefined:                1
%                            Ideal:                2
%                      VanderWaals:                3
%                         Constant:                4
%                         PowerLaw:                5
%                    SutherlandLaw:                6
%                  ConstantPrandtl:                7
%                    EddyViscosity:                8
%                   ReynoldsStress:                9
%          ReynoldsStressAlgebraic:               10
%           Algebraic_BaldwinLomax:               11
%            Algebraic_CebeciSmith:               12
%         HalfEquation_JohnsonKing:               13
%         OneEquation_BaldwinBarth:               14
%      OneEquation_SpalartAllmaras:               15
%         TwoEquation_JonesLaunder:               16
%            TwoEquation_MenterSST:               17
%               TwoEquation_Wilcox:               18
%               CaloricallyPerfect:               19
%                 ThermallyPerfect:               20
%                  ConstantDensity:               21
%                     RedlichKwong:               22
%                           Frozen:               23
%                   ThermalEquilib:               24
%                ThermalNonequilib:               25
%          ChemicalEquilibCurveFit:               26
%      ChemicalEquilibMinimization:               27
%               ChemicalNonequilib:               28
%                  EMElectricField:               29
%                  EMMagneticField:               30
%                   EMConductivity:               31
%                          Voltage:               32
%                     Interpolated:               33
%           Equilibrium_LinRessler:               34
%             Chemistry_LinRessler:               35
