%% Enumeration type CG_ElementType_t with values:
%%
%               CG_ElementTypeNull:                0
%        CG_ElementTypeUserDefined:                1
%                          CG_NODE:                2
%                         CG_BAR_2:                3
%                         CG_BAR_3:                4
%                         CG_TRI_3:                5
%                         CG_TRI_6:                6
%                        CG_QUAD_4:                7
%                        CG_QUAD_8:                8
%                        CG_QUAD_9:                9
%                       CG_TETRA_4:               10
%                      CG_TETRA_10:               11
%                        CG_PYRA_5:               12
%                       CG_PYRA_14:               13
%                       CG_PENTA_6:               14
%                      CG_PENTA_15:               15
%                      CG_PENTA_18:               16
%                        CG_HEXA_8:               17
%                       CG_HEXA_20:               18
%                       CG_HEXA_27:               19
%                         CG_MIXED:               20
%                       CG_PYRA_13:               21
%                        CG_NGON_n:               22
%                       CG_NFACE_n:               23
%                         CG_BAR_4:               24
%                         CG_TRI_9:               25
%                        CG_TRI_10:               26
%                       CG_QUAD_12:               27
%                       CG_QUAD_16:               28
%                      CG_TETRA_16:               29
%                      CG_TETRA_20:               30
%                       CG_PYRA_21:               31
%                       CG_PYRA_29:               32
%                       CG_PYRA_30:               33
%                      CG_PENTA_24:               34
%                      CG_PENTA_38:               35
%                      CG_PENTA_40:               36
%                       CG_HEXA_32:               37
%                       CG_HEXA_56:               38
%                       CG_HEXA_64:               39
%                         CG_BAR_5:               40
%                        CG_TRI_12:               41
%                        CG_TRI_15:               42
%                    CG_QUAD_P4_16:               43
%                       CG_QUAD_25:               44
%                      CG_TETRA_22:               45
%                      CG_TETRA_34:               46
%                      CG_TETRA_35:               47
%                    CG_PYRA_P4_29:               48
%                       CG_PYRA_50:               49
%                       CG_PYRA_55:               50
%                      CG_PENTA_33:               51
%                      CG_PENTA_66:               52
%                      CG_PENTA_75:               53
%                       CG_HEXA_44:               54
%                       CG_HEXA_98:               55
%                      CG_HEXA_125:               56
