%% Enumeration type CG_ModelType_t with values:
%%
%                 CG_ModelTypeNull:                0
%          CG_ModelTypeUserDefined:                1
%                         CG_Ideal:                2
%                   CG_VanderWaals:                3
%                      CG_Constant:                4
%                      CG_PowerLaw:                5
%                 CG_SutherlandLaw:                6
%               CG_ConstantPrandtl:                7
%                 CG_EddyViscosity:                8
%                CG_ReynoldsStress:                9
%       CG_ReynoldsStressAlgebraic:               10
%        CG_Algebraic_BaldwinLomax:               11
%         CG_Algebraic_CebeciSmith:               12
%      CG_HalfEquation_JohnsonKing:               13
%      CG_OneEquation_BaldwinBarth:               14
%   CG_OneEquation_SpalartAllmaras:               15
%      CG_TwoEquation_JonesLaunder:               16
%         CG_TwoEquation_MenterSST:               17
%            CG_TwoEquation_Wilcox:               18
%            CG_CaloricallyPerfect:               19
%              CG_ThermallyPerfect:               20
%               CG_ConstantDensity:               21
%                  CG_RedlichKwong:               22
%                        CG_Frozen:               23
%                CG_ThermalEquilib:               24
%             CG_ThermalNonequilib:               25
%       CG_ChemicalEquilibCurveFit:               26
%   CG_ChemicalEquilibMinimization:               27
%            CG_ChemicalNonequilib:               28
%               CG_EMElectricField:               29
%               CG_EMMagneticField:               30
%                CG_EMConductivity:               31
%                       CG_Voltage:               32
%                  CG_Interpolated:               33
%        CG_Equilibrium_LinRessler:               34
%          CG_Chemistry_LinRessler:               35
